### ISSUE TITLE
Error in TN-Ansicht

### ISSUE THREAD

**Issue by roranmorea** [Rumpelstilzli/morea#51]
Folgender Error wird geprintet, wenn man sich als TN anmeldet:

```
E/flutter ( 9407): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: No element
E/flutter ( 9407): #0      Stream.first.<anonymous closure> (dart:async/stream.dart:1254:13)
E/flutter ( 9407): #1      _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 9407): #2      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 9407): #3      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 9407): #4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
E/flutter ( 9407): #5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
E/flutter ( 9407): #6      _DelayedDone.perform (dart:async/stream_impl.dart:610:14)
E/flutter ( 9407): #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter ( 9407): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter ( 9407): #9      _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 9407): #10     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 9407): #11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 9407): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 9407): #13     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 9407): #14     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 9407): #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 9407): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 9407): #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 9407): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by roranmorea** [comment]
bleibt auch nach merge #55 bestehen. Ich nehme an, es hat irgendetwas mit Streams zu tun, welche falsch initialisiert werden.

**Comment by Rumpelstilzli** [comment]
@roranmorea schau mal ob dein User im userMap das groupID-Feld hat. Bei mir kam dieser Error, weil das groupID-Feld nicht initialisiert wurde.

**Comment by roranmorea** [comment]
hat sich gefixt
