### ISSUE TITLE
Personenverzeichnis

### ISSUE THREAD

**Issue by roranmorea** [Rumpelstilzli/morea#52]
Fehlermeldung mit rotem Bildschrim:
```
The following assertion was thrown building FutureBuilder<DocumentSnapshot>(dirty, state: _FutureBuilderState<DocumentSnapshot>#d596d):
type 'String' is not a subtype of type 'Map<dynamic, dynamic>'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

User-created ancestor of the error-causing widget was: 
  Container file:///C:/Users/Maxi/StudioProjects/morea/lib/Pages/Personenverzeichniss/personen_verzeichniss_page.dart:66:12
When the exception was thrown, this was the stack: 
#0      PersonenVerzeichnisStatePage.personen.<anonymous closure>.<anonymous closure> (package:morea/Pages/Personenverzeichniss/personen_verzeichniss_page.dart:75:128)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#2      PersonenVerzeichnisStatePage.personen.<anonymous closure> (package:morea/Pages/Personenverzeichniss/personen_verzeichniss_page.dart:75:72)
#3      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
```

**Comment by roranmorea** [comment]
bleibt bestehen auch nach merge #55
